### ISSUE TITLE
Applies to other Logitech wheels (G920)

### ISSUE THREAD

**Issue by ctospark** [kai-nightmode/logitech-g29#10]
Thank you for your great work.
I would like to apply this module for Logitech G920.
I modified the vendor and product ID in index.js to connect G920 but when I  executed 
example js file for connect, it made following error.

Error: Cannot write to HID device
    at relayOS (C:\Users\sungwoo\Documents\logitech_con\node_modules\logitech-g29\code\index.js:215:12)
    at forceConstant (C:\Users\sungwoo\Documents\logitech_con\node_modules\logitech-g29\code\index.js:388:5)
    at Object.connect (C:\Users\sungwoo\Documents\logitech_con\node_modules\logitech-g29\code\index.js:147:5)
    at Object.<anonymous> (C:\Users\sungwoo\Documents\logitech_con\connect.js:3:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

Would you mind tell me which parts should be changed to connect with G920?
Thank you for your great work.

Sungwoo

**Comment by ForestMist** [comment]
Hi and thanks. :D

It looks like the G920 is the Xbox version of a Logitech Wheel ya?

Sounds like you found the wheel by changing the vendor and product ID so that is good news. Then it gets stuck trying to send a movement command to the wheel in order to see which wheel mode the G920 is in. Not sure if detecting the low or high precision wheel mode is necessary for this particular wheel though. I don't have a G920 to experiment on so I can only offer you some ideas to try.

**Ideas to try in `logitech-g29\code\index.js`**

- Hard code the variable `prependWrite` to false to see if that helps the `relayOS` function.
- Hard code the variable `prependWrite` to true to see if that helps the `relayOS` function.
- Inside the `connect` function, disable the call to `forceConstant(1)` at the bottom and instead gently nudge the wheel when you start the program to generate a move event. The move event is needed to see what format the wheel sends data back in. Low or high precision modes. If low precision mode is detected, the G29 wheel init may be attempted in which case if you have trouble writing to the wheel, it will likely crash again.

I'm not sure how much I can help but if you find that you make a tiny bit more progress before getting stuck at the next thing, let me know.

**Comment by ForestMist** [comment]
Hey ctospark,

Can you run `node ./test/hid-devices.js` and then search for G920 and post the object (or objects) you find?

Here is my G29 object. Ignore the productId since I'm having an issue with that currently.

```js
{
    vendorId: 1133,
    productId: 49812,
    path: 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS11@14600000/G29 Driving Force Racing Wheel@14600000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14600000,0',
    serialNumber: '',
    manufacturer: 'Logitech',
    product: 'G29 Driving Force Racing Wheel',
    release: 4944,
    interface: -1,
    usagePage: 1,
    usage: 5
}
```

**Comment by marcusround** [comment]
Hi,
Appreciate this may be old/dormant but I'm very interested + motivated to get this working with the G920. I ran that command and here is what I get. It comes up three times in the results so I'm just pasting all of them here:

```
  {
    vendorId: 1133,
    productId: 49762,
    path: '\\\\?\\hid#vid_046d&pid_c262&col01#7&12179689&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: '0000ec5205d34feb',
    manufacturer: 'Logitech',
    product: 'G920 Driving Force Racing Wheel for Xbox One',
    release: 38404,
    interface: -1,
    usagePage: 1,
    usage: 4
  },
  {
    vendorId: 1133,
    productId: 49762,
    path: '\\\\?\\hid#vid_046d&pid_c262&col02#7&12179689&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: '0000ec5205d34feb',
    manufacturer: 'Logitech',
    product: 'G920 Driving Force Racing Wheel for Xbox One',
    release: 38404,
    interface: -1,
    usagePage: 65347,
    usage: 1538
  },
  {
    vendorId: 1133,
    productId: 49762,
    path: '\\\\?\\hid#vid_046d&pid_c262&col03#7&12179689&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: '0000ec5205d34feb',
    manufacturer: 'Logitech',
    product: 'G920 Driving Force Racing Wheel for Xbox One',
    release: 38404,
    interface: -1,
    usagePage: 65347,
    usage: 1540
  },
```
